### ISSUE TITLE
Cannot view collections that a user is invited to

### ISSUE THREAD

**Issue by Mathis-Z** [openHPI/codeharbor#1147]
When you recieve an invitation to a collection the invitation has a "View" button. Clicking this button leads to a "not authorized" error because you cannot view collections before you accepted the invitation.

**Comment by MrSerth** [comment]
I would assume that this error has been fixed with #1184. Can you confirm whether that's true or whether the issue still exists?

**Comment by Mathis-Z** [comment]
I can confirm that the bug was resolved, however during testing I noticed a new bug which I opened another ticket for: #1668
