### ISSUE TITLE
Viewing tasks is no longer possible as anonymous user

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#1186]
Today, I've noticed that viewing a public tasks without being logged in is no longer possible. This is probably a regression introduced by #1134.

Consider the task having ID 89: 
- Viewing the IEEE LOM format is possible: https://codeharbor.openhpi.de/bridges/lom/tasks/89
- Downloading the ProFormA XML is _NOT_ possible: https://codeharbor.openhpi.de/tasks/89/download
- Viewing the task in the browser is _NOT_ possible: https://codeharbor.openhpi.de/tasks/89

**Comment by kkoehn** [comment]
For me the ProForma XML link does also NOT work

**Comment by MrSerth** [comment]
Ah, right -- same for me. Obviously, I switched to the wrong, non-private window to test that 🙈
