### ISSUE TITLE
New search does not reset current page

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#1197]
It might happen that a new search returns no results, even though matching entries are available. Specifically, that's the case when less search results than the current page would normally list are available. 

Steps to reproduce: 

1. Ensure there are X tasks with a given title, with X being the number of tasks being shown per page. 
2. Add another task with a unique title. 
3. Visit the second page. 
4. Search for the unique title.
5. See that no results are returned. If you repeat the reproduction steps, but enter a search term while viewing the first page, the search works as expected. 

<hr>

This bug is probably a combination of pagination and the usage of ransack as our search engine.

**Comment by Mathis-Z** [comment]
This seems to have been fixed by Karol in October 22. This is the line: 
https://github.com/openHPI/codeharbor/blob/0f1b778fa05dd33718b581d804e91b85f3535260/app/assets/javascripts/tasks_index.coffee#L76

**Comment by MrSerth** [comment]
Since I've reported the issue in January 2024 and Karol's commit is from October 2022, it doesn't seem to be reliably fixed. Furthermore, I was just able to reproduce it, here is a screencast:


https://github.com/user-attachments/assets/a6f321b2-b4ba-48f4-86ef-fe6fbedbba46

**Comment by Mathis-Z** [comment]
I think I know what causes this: In your screencast you enter a new search term and then submit it by pressing enter. This does not run the onchange callback again. When you submit it by clicking on "Search", the onclick handler is executed correctly.
