### ISSUE TITLE
TaskFiles: Cannot be referenced multiple times

### ISSUE THREAD

**Issue by kkoehn** [openHPI/codeharbor#1371]
In ProFormA files can be referenced to multiple times.
This is currently not possible, since the relation of `TaskFile` to `fileable` is one-to-one relation.

The relation would have to be change to one-to-many.
The UI-Elements (esp. Editors) have to support this.

successor of #1249

**Comment by kkoehn** [comment]
A temporary solution for the import has been implemented in #1370. Instead of referencing multiple times, the files involved get duplicated.

**Comment by MrSerth** [comment]
> A temporary solution for the import has been implemented in #1370. Instead of referencing multiple times, the files involved get duplicated.

Thanks! I found another edge case in our temporary solution, requiring some further adjustments. See https://github.com/openHPI/codeharbor/pull/1370#issuecomment-2132142921.

**Comment by MrSerth** [comment]
This issue should be resolved with #1426, I assume. Can we close it, @kkoehn?

**Comment by kkoehn** [comment]
Yes, it should be fixed now
