### ISSUE TITLE
ZIP download broken

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#224]
When downloading an exercise as ZIP archive, a white page is displayed being served by an HTTP 500 response. I was not able to find any exercise (such as ID 13 or 15) that allowed me to download an archive successfully.

**Comment by kkoehn** [comment]
Strange issue!
While I'm too not able to download an already existing exercise (500) or even edit it (422). I can however create a new one and download (and edit) it without problems.

There were definitely some validations added which might be the root of the errors. It's difficult to say without a stacktrace from the server or console access.

**Comment by MrSerth** [comment]
Thanks for having a look. I'll organize a stack trace and provide more information. Setting up some kind of monitoring is another task I would like to do.

**Comment by kkoehn** [comment]
For future reference a list of added validations:
```
  validates :descriptions, presence: true
  validates :execution_environment, presence: true, unless: :private?
  validates :license, presence: true, unless: :private?
  validate :no_predecessor_loop, :one_primary_description?, :valid_main_file?

  validates_uniqueness_of :uuid
```

**Comment by kkoehn** [comment]
@MrSerth #230 might also with this issue

**Comment by MrSerth** [comment]
I'll try to get #232 merged soon and get the missing information. Otherwise, we could try again after merging #230 .

**Comment by kkoehn** [comment]
#230 won't fix the issue on its own, but would provide direct access to the database objects. I may be able to figure out the problem with the old exercises through there.

**Comment by kkoehn** [comment]
Oh nice you already merged it. I was waiting for your review and didn't even see that you already did it. 

To do the debugging I'd now need the admin-role (either through the console or rails-admin). And it would have to be deployed first of course.

**Comment by MrSerth** [comment]
I finally managed the deployment and reproduced the error. I guess, the missing primary description caused the error. I attached a stack trace of the issue.

Further, I encountered issue #235 deploying the new release due to the precompilation of assets.

![Bildschirmfoto 2020-01-17 um 14 42 33](https://user-images.githubusercontent.com/7300329/72616666-b4f28a80-3937-11ea-868c-8a4fcfd1f380.png)

**Comment by kkoehn** [comment]
I somehow doubt that that is the only issue. I'd probably prefer to find all model related errors first. 
I get a 422 when trying to update an old exercise (ie ID: 22)

I'd say lets fix one exercise to the point where everything works again and analyze all necessary steps and if they can occur again or are owed to the old structure.

**Comment by MrSerth** [comment]
I noticed that, it is related to the primary description as well.
Furthermore, I granted additional permissions through Rails Admin, you should be able to access these pages now.

![Bildschirmfoto 2020-01-17 um 15 13 22](https://user-images.githubusercontent.com/7300329/72618699-f38a4400-393b-11ea-9642-dea5de990b99.png)

**Comment by kkoehn** [comment]
The two main things that i found are: 

- the primary description problems you found (one in a validation, one in the converter)
- multiple main_files. (this should be fixable through an easy edit)

I think i would prefer fixing the primary descriptions in the database. And let the user fix the rest himself (They should get the validation errors afterwards)

**Comment by kkoehn** [comment]
This one-liner should do the trick

```
Exercise.all.filter{|e|e.descriptions.select(&:primary?).blank?}.each{|e|e.descriptions.first.update(primary: true)}
```

**Comment by MrSerth** [comment]
Thanks, I executed that one.
Further, some exercises had an empty description, which did not update correctly. I changed these as well, so that no blank primary descriptions are left.
```
Exercise.all.filter{|e|e.descriptions.select(&:primary?).blank?}
=> []
```

**Comment by kkoehn** [comment]
nice, this issue is fixed then?

**Comment by MrSerth** [comment]
I guess so. What about the two problems you mentioned above? We fixed the primary description issue but I am unsure about the multiple main_files thing.

**Comment by kkoehn** [comment]
Good point. I just checked:

- You are able to download the exercise 
- You can edit the exercise (while updating, it will give you a validation error which you need to fix).
- You won't be able to export it to CO, the validation there should catch it.

The safest way would probably be to validate each exercise before exporting/downloading, but I'm not sure that's really necessary

**Comment by MrSerth** [comment]
Alright, thanks for the clarification. I checked these and fixed them where needed:
```
Exercise.all.filter{|e| !e.valid? }.pluck(:id)
=> []
```

However, I found many inconsistencies in the database for which I've open issue #241.
As the bug reported originally is now resolved, I closed this one.
