### ISSUE TITLE
Check database inconsistencies and model validations

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#241]
While working on #224, I noticed a few strange things in our database. I propose to perform these two steps (am I missing more?):

- [x] delete / fix invalid data from the database
- [x] ensure we have model validations / and proper dependents settings (such as `dependent: :destroy`) to prevent these errors in the future

I found these relations which might be problematic:

- [x] Account link users: Are these still used? How (through groups?)?
- [x] Carts without a user (empty carts are okay, I assume?)
- [x] Collections without any user
- [x] Description without exercise
- [x] Exercise authors: Are these still used?
- [x] Exercise files without exercise
- [x] (Exercise group accesses?)
- [x] Exercise lables without exercise
- [x] Messages with no sender status / recipient status
- [x] Relations without exercise relations
- [x] Tests without exercise

Some of them might be okay, I was just unsure about these.

**Comment by kkoehn** [comment]
> * Account links: Are these still used? How?
We use AccountLink to save the data that is necessary to connect to other APIs (mainly CO right now)
> * Carts without a user (empty carts are okay, I assume?)
AFAIK one user should have one cart. Carts without a user should not exist. Users without a cart should get one.
> * Collections without any user
Not quite sure, but doesn't seem to make sense

**Comment by MrSerth** [comment]
Thanks for your quick reply, I did not finish my issue yet when sending so that I edited it a few moments later.

**Comment by MrSerth** [comment]
> > * Account links: Are these still used? How?
> 
> We use AccountLink to save the data that is necessary to connect to other APIs (mainly CO right now)

For sure. I intended to ask Account Link users as I though that now every user holds a unique account link.

> 
> > * Carts without a user (empty carts are okay, I assume?)
> 
> AFAIK one user should have one cart. Carts without a user should not exist. Users without a cart should get one.

Does every user has one cart at all times or is that dynamic, so that the cart is only created once I open the page / add something to my cart?

> 
> > * Collections without any user
> 
> Not quite sure, but doesn't seem to make sense

I agree.

**Comment by kkoehn** [comment]
@MrSerth updated my reply

**Comment by kkoehn** [comment]
On the matter of AccountLinkUser: I'm not sure. I have seen that multiple times now and yes I think it should work through groups somehow. Have not tested that yet

**Comment by MrSerth** [comment]
### General reply:

Thanks. Maybe @tstaubitz knows more?
The longer I dig into the database, the more questions I get. Another one is: How could an exercise become a "group member" of a group? (Relation `Group memberships` as `member`)
And how could one group membership with the same member, group and membership type exist twice? What is the group name in that relation for?

Would you do me a favor and have a look at that data and implement validations where necessary or propose schema changes? Otherwise, I fear data corruption once we imported all existing exercises from CodeOcean. On Friday, @tstaubitz and I agreed on deleting data (or whole relations) instead of fixing all errors manually to get ready for production usage.

----

### Reply on individual relations:

Regarding AccountLinkUser: As a group member, I might grant push privileges to another user. That will show up as AccountLinkUser.

Regarding Carts: A second user I created got a new cart on account creation. So that might only affect existing users.

ExerciseAuthor: Yep, you're right

ExerciseGroupAccess: Relation exists, but is empty. I don't know how it is used.

**Comment by MrSerth** [comment]
Further, I found duplicate file types in the database, which we should eliminate as well.

**Comment by MrSerth** [comment]
... and I found exercise files without any file type.

**Comment by kkoehn** [comment]
> ### General reply:
> Thanks. Maybe @tstaubitz knows more?
> The longer I dig into the database, the more questions I get. Another one is: How could an exercise become a "group member" of a group? (Relation `Group memberships` as `member`)

I'm not exactly sure how the `groupify` gem works, but it enables you to create a `Group` and add members to it based on a polymorphic relation. In this case users and exercises. The users are the supposed to have access to the exercises. (This seems to work based on my experience)
> And how could one group membership with the same member, group and membership type exist twice? 

There is simply no validation that prevents it. This may cause an issue, when you are trying to remove the membership. This should be fixed imo.

> What is the group name in that relation for?

I don't think it is used.

> Would you do me a favor and have a look at that data and implement validations where necessary or propose schema changes? Otherwise, I fear data corruption once we imported all existing exercises from CodeOcean. On Friday, @tstaubitz and I agreed on deleting data (or whole relations) instead of fixing all errors manually to get ready for production usage.

I will (try to) fix everything I find, but have no hopes of finding everything.
> 
> ### Reply on individual relations:
> Regarding AccountLinkUser: As a group member, I might grant push privileges to another user. That will show up as AccountLinkUser.

Does that actually work? Did you test it?

> Regarding Carts: A second user I created got a new cart on account creation. So that might only affect existing users.

> 
> ExerciseAuthor: Yep, you're right
> 
> ExerciseGroupAccess: Relation exists, but is empty. I don't know how it is used.

I will have a look

**Comment by MrSerth** [comment]
> > ### General reply:
> > Thanks. Maybe @tstaubitz knows more?
> > The longer I dig into the database, the more questions I get. Another one is: How could an exercise become a "group member" of a group? (Relation `Group memberships` as `member`)
> 
> I'm not exactly sure how the `groupify` gem works, but it enables you to create a `Group` and add members to it based on a polymorphic relation. In this case users and exercises. The users are the supposed to have access to the exercises. (This seems to work based on my experience)

Okay, if that works as intended, I am fine. I don't know the `groupify` gem either, so that's why I ask.

> > And how could one group membership with the same member, group and membership type exist twice?
> 
> There is simply no validation that prevents it. This may cause an issue, when you are trying to remove the membership. This should be fixed imo.

:+1:

> > What is the group name in that relation for?
> 
> I don't think it is used.
> /e: It's part of the groupify implementation. See https://github.com/dwbutler/groupify#named-groups
> I would leave it there, even though it is not used right now.

🆗 

> > Would you do me a favor and have a look at that data and implement validations where necessary or propose schema changes? Otherwise, I fear data corruption once we imported all existing exercises from CodeOcean. On Friday, @tstaubitz and I agreed on deleting data (or whole relations) instead of fixing all errors manually to get ready for production usage.
> 
> I will (try to) fix everything I find, but have no hopes of finding everything.

Awesome! The more we find and fix, the better. And we'll fix the rest once we discover these.

> > ### Reply on individual relations:
> > Regarding AccountLinkUser: As a group member, I might grant push privileges to another user. That will show up as AccountLinkUser.
> 
> Does that actually work? Did you test it?

No and No. I didn't test earlier, but did today: It does not work, as the account link is not selectable by the other user.

> 
> > Regarding Carts: A second user I created got a new cart on account creation. So that might only affect existing users.
> 
> > ExerciseAuthor: Yep, you're right
> > ExerciseGroupAccess: Relation exists, but is empty. I don't know how it is used.
> 
> I will have a look

🙂

**Comment by kkoehn** [comment]
I think with #266 we addressed all issues in here.

**Comment by MrSerth** [comment]
I tried to get an overview of the recent changes and re-validated the bullet points. Before closing this issue, I would also like to ensure our production system is valid without any irregularities. 

However, I think not all models are valid yet. Probably, some old inconsistencies occurred before Rails 5 and the change in [`belongs_to`](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-belongs-to-required-by-default-option]). Previously, `belongs_to` was optional and is now required. Some code still refers to the old behavior,e.g. by setting `optional: false`.

Do you think that checking all records with the `valid?` method and taking care of those invalid ones (e.g. update or delete) is sufficient to bring our database back to a consistent state?

To help track changes, I added checkboxes to my initial post regarding the current status of required changes. Many of them are database related, I guess.

**Comment by kkoehn** [comment]
> I found these relations which might be problematic:
> 
> * [x]  Account link users: Are these still used? How (through groups?)?
> * [ ]  Carts without a user (empty carts are okay, I assume?)

Has validations and dependency settings
> * [ ]  Collections without any user

Has dependency settings. Validation added in new PR
> * [ ]  Description without exercise

Has validations and dependency settings
> * [x]  Exercise authors: Are these still used?
> * [ ]  Exercise files without exercise

Exercise files can also belong to a test (it's currently a has_many relationship, which should be fixed)
> * [x]  (Exercise group accesses?)

VVVVVV WIP VVVVVV
> * [ ]  Exercise lables without exercise
> * [ ]  Messages with no sender status / recipient status
> * [ ]  Relations without exercise relations
> * [ ]  Tests without exercise
> 
> Some of them might be okay, I was just unsure about these.

**Comment by MrSerth** [comment]
Alright, I am so glad you took the time to look into this. I rechecked the entries and fixed and invalid entries I found. Do you think, there is anything missing? Otherwise, I would propose to close this issue.

**Comment by MrSerth** [comment]
Closing this for now. If we find any additional issues, we'll open another one.
