### ISSUE TITLE
Check interoperability with other files

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#250]
We designed CodeHarbor to work with ProFormA in order to allow easier file exchange. Let's test that with [these scripts](https://github.com/ProFormA/examples/tree/master/proforma_v2.0.x/ostfalia/task), they should follow the current standard and were create with this [Moodle plugin](https://moodle.org/plugins/qtype_proforma).

**Comment by kkoehn** [comment]
The provided files are referencing `xmlns="urn:proforma:v2.0"` the most recent `.xsd` is `v2.0.1` and won't allow any other version.
We should think about a way to handle such a situation in the future, I'm currently not sure what the best approach would be. 

I'll manually edit the files to fix the version and test those with our importer for now.

**Comment by kkoehn** [comment]
List of problems during import:
- No feedbackmessage and testing-framework (we use our own namespace here). It's not mandatory, therefore an easy fix
  - Testingframework is in there, but under its own namespace, will check that.
- In Proforma Tests can have an arbitrary amount of files. We need them to have exactly one file. Not sure how to approach this. The Test structure would have to be reworked and might be incompatible with the structure in CO. - I will just import the files separately for now, but ignore tests without files. 
- We use the `internal-description` of exercise files to store the `role` - this will probably cause problems down the line.

**Comment by MrSerth** [comment]
Sorry for my late reply. I just took the time to check the current status and tried the import myself.

- feedback-message
  - The feedback-message is mandatory when importing to CodeOcean, right? Can we ensure to provide a general error message such as "Your programm does not meet the test requirements. Please check the output for more information"?
- testing-framework
  - You tackled that with the PR as far as I can see? Sure, manual editing is required to get the best results
- number of test files
  - In CodeOcean, I would also import each file separately. The test file referenced for execution would be a `teacher_defined_test` and others a `hidden` `regular_file`. Could we project this to CodeHarbor? I also noticed with the `reverse.zip` example that the test case was not properly imported. Is this due to the two files included?
- empty test files
  - I am fine ignoring those.
- internal-description
  - Yes, I guess, it's not the right place to put our roles. How is the `task-file-type` used?
- Main File
  - Yes, we need to add one manually. Other grades don't require these but CO does.

Additionally, I stumbled accross those issues:

- HTML entities
  - The examples include words such as `Anf&uuml;hrungsstriche` instead of `Anführungsstriche`. It seems CodeHarbor does not handle these correctly. Especially when re-exporting a previoulsy imported exercise, the result is not satisfying (`Anf&amp;uuml;hrungsstriche`)
- Formatted description
  - The examples use HTML code, we do use Markdown. Any chance to handle that correctly? I could open a new issue, if you'd like.
- `visible="delayed"`
  - For reference implementations with `visible="delayed"`, the importer defauls to `visible`. I would prefer to have those not visible if only two options are available.

**Comment by MrSerth** [comment]
Regarding the validity with `xmlns="urn:proforma:v2.0"`:

I will check back with the ProFormA group. Could we ignore the minor version without much work?

**Comment by kkoehn** [comment]
I think for the moment we could just go back to 2.0, since there was no official 2.0.1 release. But it may make sense to allow both 2.0 and 2.1 in the future. I will try to adapt the proforma-gem in a way that it supports different schemas at the same time.

**Comment by kkoehn** [comment]
Do you have an overview what changes were made between the release of 2.0 and now?

**Comment by MrSerth** [comment]
> I think for the moment we could just go back to 2.0, since there was no official 2.0.1 release. But it may make sense to allow both 2.0 and 2.1 in the future. I will try to adapt the proforma-gem in a way that it supports different schemas at the same time.

Ok, great. Sounds good!

> Do you have an overview what changes were made between the release of 2.0 and now?

Unfortunately not. I think the release notes are still pending. As far as I remember, the changes were not too critical for us.

**Comment by kkoehn** [comment]
> Sorry for my late reply. I just took the time to check the current status and tried the import myself.
> ...

I should have tackled almost all your points here.

> Additionally, I stumbled accross those issues:
> 
> * HTML entities
>   
>   * The examples include words such as `Anf&uuml;hrungsstriche` instead of `Anführungsstriche`. It seems CodeHarbor does not handle these correctly. Especially when re-exporting a previoulsy imported exercise, the result is not satisfying (`Anf&amp;uuml;hrungsstriche`)



I found the gem `kramdown` to easily convert between markdown and html
One problem though: when converting from markdown to html, I'm not able to use the html entity for the Umlaute. I suspect, that it is not mapped in the gem internally as other html entities convert just fine. I don't see that as a big problem since utf-8 should be able to handle everything well and the import would work.

> * Formatted description
>   
>   * The examples use HTML code, we do use Markdown. Any chance to handle that correctly? I could open a new issue, if you'd like.

I was also not aware that we use markdown for descriptions. In CH that doesn't seem to be the case.
Descriptions right now get displayed as unformatted string, while line breaks and such are saved in the database.

**Comment by MrSerth** [comment]
> I should have tackled almost all your points here.

Great, thanks!

> I found the gem `kramdown` to easily convert between markdown and html
> One problem though: when converting from markdown to html, I'm not able to use the html entity for the Umlaute. I suspect, that it is not mapped in the gem internally as other html entities convert just fine. I don't see that as a big problem since utf-8 should be able to handle everything well and the import would work.

Using `kramdown` is fine, thanks. And I don't mind if we don't generate these html entities ourselfes; we should just read them correctly.

> > * Formatted description
> >   
> >   * The examples use HTML code, we do use Markdown. Any chance to handle that correctly? I could open a new issue, if you'd like.
> 
> I was also not aware that we use markdown for descriptions. In CH that doesn't seem to be the case.
> Descriptions right now get displayed as unformatted string, while line breaks and such are saved in the database.

In CO, we also use `kramdown` for rendering. In our views, we simply call `render_markdown(@exercise.description)` to show a rendered version of the exercise. Unfortunately, some of the exercise descriptions we have on CO still use some HTML-flavored markdown, e.g. for lists (with the `<ul><li>Element</li></ul>` syntax). However, `kramdown` handles these cases as well. Or shall we convert markdown to HTML before exporting from CO?

**Comment by kkoehn** [comment]
> In CO, we also use `kramdown` for rendering. In our views, we simply call `render_markdown(@exercise.description)` to show a rendered version of the exercise. Unfortunately, some of the exercise descriptions we have on CO still use some HTML-flavored markdown, e.g. for lists (with the `<ul><li>Element</li></ul>` syntax). However, `kramdown` handles these cases as well. Or shall we convert markdown to HTML before exporting from CO?

I decided to store the descriptions as MD in CH for now - though it is not rendered yet, that would be its own feature if we want to do that later.
I don't think we have to convert it to html in CO, it should convert from MD to MD just fine (but we should probably try it to be sure)
I implemented the conversion in #400, but I'm not sure whether I should handle that in the gem or in the application itself.

**Comment by MrSerth** [comment]
> > In CO, we also use `kramdown` for rendering. In our views, we simply call `render_markdown(@exercise.description)` to show a rendered version of the exercise. Unfortunately, some of the exercise descriptions we have on CO still use some HTML-flavored markdown, e.g. for lists (with the `<ul><li>Element</li></ul>` syntax). However, `kramdown` handles these cases as well. Or shall we convert markdown to HTML before exporting from CO?
> 
> I decided to store the descriptions as MD in CH for now - though it is not rendered yet, that would be its own feature if we want to do that later.
> I don't think we have to convert it to html in CO, it should convert from MD to MD just fine (but we should probably try it to be sure)
> I implemented the conversion in #400, but I'm not sure whether I should handle that in the gem or in the application itself.

Thanks! I think, handling it in the application is fine because it makes the gem easier to reuse in multiple occasions (even without using markdown, or html but some other formats). Then, it is always the responsibility of the application to provide an html-based description.
Regarding file exchange between CO and CH: How would you handle the markdown export? That is not included in #400 so far, right?

**Comment by kkoehn** [comment]
> Regarding file exchange between CO and CH: How would you handle the markdown export? That is not included in #400 so far, right?

You are right. I added it now.
I added it so it will always use Markdown when exporting to another app for now. In the future this could be an option configurable for the AccountLink.

**Comment by MrSerth** [comment]
> > Regarding file exchange between CO and CH: How would you handle the markdown export? That is not included in #400 so far, right?
> 
> You are right. I added it now.
> I added it so it will always use Markdown when exporting to another app for now. In the future this could be an option configurable for the AccountLink.

Okay, that's a good option. As long as we only export between CO and CH, you're right and this could be set fixed to MD.

**Comment by kkoehn** [comment]
I tried im- and exporting the helloWorld example with the new changes in https://github.com/openHPI/proforma/pull/303 and noticed a few differences:
1. in the example all text nodes contain a cdata-node which contains the actual content (in html), our export converts the (potential markdown to html) and encodes the special symbols
2. some nodes are missing from task:
  - submission-restrictions
  - grading-hints

The problem with the missing nodes is, that we are not keeping track of which nodes we actually take into account, so we would have to add missing nodes by hardcoding them into the import-process (where they might be converted to json and just saved as is)

The goal is still to be able to import a valid proforma (task?)file with any information and export it again without loss of information right?

**Comment by MrSerth** [comment]
Thanks for checking! Do you actually have the resulting export at hand, so that I can compare these as well? Probably, this would make it easier for me to follow your thoughts.

1. This doesn't sound too bad to me. I would consider a CDATA tag and the escaped version to be semantically equal -- but of course, I am not an expert here.
2. This seems to be an issue, since we are loosing some information. As you pointed out in your question: Yes, the goal would be to import and export a valid ProFormA file without data / information loss.

I get the issue you are describing with the missing nodes during import. But can't we either "mark" them in the Nokogiri XML structure anyhow or alternatively identify the remaining ones by comparing the original XML against one (temporary) XML re-created from the imported nodes? Or otherwise have a default method that is called for those elements and stores those information in a JSON for dachsfisch?

**Comment by kkoehn** [comment]
I added the original and re-exported file below: I re-exported the file using the proforma-gem directly


[helloWorld.zip](https://github.com/openHPI/codeharbor/files/11995058/helloWorld.zip)
[exported_helloWorld.zip](https://github.com/openHPI/codeharbor/files/11995057/exported_helloWorld.zip)

**Comment by kkoehn** [comment]
2: as far as I can see the following attributes are missing (from the proforma-gem and CH respectively):
- task
  - submission-restrictions
  - external-resources
  - grading-hints
I think adding those attributes manually and storing the (dachsfisched) json could make sense.

**Comment by kkoehn** [comment]
@MrSerth should be fixed with #990 
please check again

**Comment by MrSerth** [comment]
I just took some time to test our ProFormA implementation and also cover how our files (and the original files) are treated in the two Moodle plugins I have access to. Here are my results:

- The MooPT plugin is not capable of handling a missing `internal-description` and will add the value `undefined` during import. I consider this to be a bug of the MooPT plugin (since ProFormA explicitly states that 0 occurrences of the tag are allowed), and therefore would not change anything here.
- The MooPT plugin only supports version 2.1.
- The ProFormA plugin only started to support `embedded-bin-files` recently, older versions are incompatible. Since the newest version adds support, we don't need to change anything here either.
- The ProFormA plugin only supports versions 1.x, 2.0 and 2.0.1, but not the newest version 2.1. Therefore, it would be great to allow users in CodeHarbor to select the version during export. See #1094.
- The ProFormA plugin handles the optional attribute `usage-by-lms` differently than we do: In their implementation, the absence of the attribute means that the file is not offered for download in the LMS. However, we treat a missing attribute as the default, which is `usage-by-lms = "download"`. Thus, if we import a ProFormA task ([example](https://github.com/openHPI/codeharbor/files/13391830/helloWorld.zip)) with the `usage-by-lms` missing and re-export the same task, the behaviour in Moodle will change. We should check that with the [ProFormA Whitepaper](https://github.com/ProFormA/proformaxml/blob/master/Whitepaper.md#the-file-element) again to decide whether it's a bug or feature...
- Due to the markdown rendering of the description, we are always adding the text within a `<p>` tag -- even if the description important just contains plain text (neither HTML nor Markdown). [Here](https://github.com/openHPI/codeharbor/files/13391986/isPalindromPackage.zip) is an example of such a case, where the description is (originally) just a single word. 

Further, I identified the following problems during my testing:

- https://github.com/openHPI/proformaxml/issues/360
- https://github.com/openHPI/proformaxml/issues/361
- https://github.com/openHPI/codeharbor/issues/1092
- https://github.com/openHPI/codeharbor/issues/1093
- https://github.com/openHPI/codeharbor/issues/1094
- https://github.com/openHPI/codeharbor/issues/1095

Let's quickly discuss the two open topics from the first list (`usage-by-lms`, `description` rendering) and then close this issue (since we have the others to follow up).

**Comment by kkoehn** [comment]
I think both issues are fix-worthy
- the default for `usage-by-lms` was added intentionally, but I can't remember why
- the added `<p>` for the description doesn't seem intutitve
