### ISSUE TITLE
Fix show on exercise_files

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#251]
Currently, a route exists to inspect a single exercise file, such as `GET /exercise_files/100`. However, opening the link results in an Internal Server Error. Do we need that route or could it be deleted? 

---

Sentry Issue: [CODEHARBOR-6]

```
NoMethodError: undefined method `main' for #<ExerciseFile:0x00007fc2609dd6e8>
  app/views/exercise_files/show.html.slim:6:in `_app_views_exercise_files_show_html_slim___1778001577818922014_70236406985220'
    = @exercise_file.main
...
(123 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `main' for #<ExerciseFile:0x00007fc2609dd6e8>
```

**Comment by kkoehn** [comment]
Is there also a path to that route or did you just try do access it directly?

**Comment by MrSerth** [comment]
I (accidentally) used the link from Rails admin to open the page and was surprised that some route exists and that the app tried to render anything. Our `routes.rb` also includes `resources :exercise_files`, which created that route. There might even be more routes we don't want or need.

**Comment by kkoehn** [comment]
I'm on it. 
I'd like to purge the "old" admin route/pages in favor of rails admin. What do you think about that?

**Comment by MrSerth** [comment]
In general, I really like the idea as it helps us to maintain the admin backend much easier. There are a very few, rarely used features not that easy with Rails admin, especially that that require additional care when updating (e.g. changing a password for another user, or getting a notification if data is not entered correctly -- such as for an invalid user role or adding members to a group and forgetting to adopt the role). I assume we won't get these features for free and as they are not that important, I would deal with that. The only remaining question is whether Rails admin would allow me to check my data prior to updating it (could be a separate action) in case I am unsure about the validation. If not, that's okay for me.
Either way, I am fine if we focus on the user-facing part of the app and simply use Rails admin for everything admins need to do.

**Comment by kkoehn** [comment]
Rails admin does support custom actions, but if you break a validation it can't save anyway and will notify you accordingly.
We should probably add validations for the cases that might cause issues.

**Comment by MrSerth** [comment]
Sounds good! 👍
