### ISSUE TITLE
Production issues

### ISSUE THREAD

**Issue by kkoehn** [openHPI/codeharbor#299]
- I just tested production and noticed two errors:
  - most of the exercise are not showable (500)
  - after an error occurs and you go back, the styling of the error page somehow persists and centers the whole page.

I'll look into the second problem, but need logs for the first one.

**Comment by MrSerth** [comment]
I got notified of two new issues and assume these are related to the errors you discovered:

---

Sentry Issue: [CODEHARBOR-B]
`/exercises/13/duplicate`

```
NoMethodError: undefined method `duplicate' for nil:NilClass
  app/models/test.rb:49:in `duplicate'
    test_duplicate.exercise_file = exercise_file.duplicate(test: test_duplicate)
  app/models/exercise.rb:298:in `map'
    tests.map(&:duplicate)
  app/models/exercise.rb:298:in `duplicate_tests'
    tests.map(&:duplicate)
  app/models/exercise.rb:224:in `block in duplicate'
    exercise.tests = duplicate_tests
  app/models/exercise.rb:223:in `tap'
    ).tap do |exercise|
...
(97 additional frame(s) were not displayed)
```


---
Sentry Issue: [CODEHARBOR-C]
`/exercises/22`

```
NoMethodError: undefined method `+' for nil:NilClass
  app/views/exercises/show.html.slim:339:in `block in _app_views_exercises_show_html_slim___218117086073712475_69818486491020'
    = link_to acc_link.name + (acc_link.user != current_user ? " (#{t('.account_link_shared')})" : ''), export_external_start_exercise_path(account_link: acc_link), method: :post, remote: true, class: 'dropdown-item export-test'
  app/views/exercises/show.html.slim:337:in `each'
    - current_user.available_account_links.each do |acc_link|
  app/views/exercises/show.html.slim:337:in `_app_views_exercises_show_html_slim___218117086073712475_69818486491020'
    - current_user.available_account_links.each do |acc_link|
...
(131 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `+' for nil:NilClass
```

**Comment by kkoehn** [comment]
I submitted a validation and suggestion in #303 to fix one of the problems (the middle one)
The others occur when a test has no associated `ExerciseFile` there is a validation for that already, so we would only have to supply them with a file.

**Comment by kkoehn** [comment]
@MrSerth could you please fix the other problem by executing:
```
Test.all.filter{|test| test.exercise_file.nil?}.each{|test| test.update(exercise_file: ExerciseFile.find(118).duplicate(test: test))}
```

This should assign a dummy `exercise_file` to all the tests missing one

**Comment by MrSerth** [comment]
@kkoehn Sure, I did that. I somehow wondered why I did not find these issues in #284, where I was supposed to do so. I am very sorry about that. As of now:

``` ruby
Test.all.select { |t| t.exercise_file.nil? }
=> []
```

**Comment by kkoehn** [comment]
Thanks.
Yeah, that is weird, maybe my migration in #284 didn't work for all tests or something else is going on. I'll keep an eye on that.
