### ISSUE TITLE
Push to external account from exercises

### ISSUE THREAD

**Issue by leoselig** [openHPI/codeharbor#4]
*Issue describes OAuth2 (Grant Type: Authorization Code) and is based on https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2*

**Flow:**
1. Log in to CodeHarbour
2. Navigate to "Link external account"
3. Paste URL to OAuth2 provider (e.g. CodeOcean) into field and proceed
4. ~~User is redirected to OAuth2 URL and permits access~~
5. ~~OAuth2 provider redirects user back to CodeHarbour (redirect URI) passing authorization code~~
6. ~~CodeHarbour uses authorization code to request access token~~
4.-6. After discussion: user just copy/pastes access token from provider (e.g. CodeOcean) to CodeHarbour
7. Store access token and resource servers' host in database (latter will be used for the URL to push the learning resources to later)

**Possible Gems to use:**

- https://github.com/doorkeeper-gem/doorkeeper
- https://github.com/intridea/oauth2

Tasks:
- [x] Add dropdown with all account links to exercise views
- [x] Send empty HTTP POST to the push URL of the selected account link

**Comment by rteusner** [comment]
lgtm, however I think we can omit the (automatic) steps 4, 5 and 6 and insert these values directly. (If I got Toms comment right that we want to have this as a gateway function, so that the platform admins have to talk about this)

**Comment by leoselig** [comment]
Okay
So the OAuth2 provider (e.g. CodeOcean) generates the token manually for the user to copy/paste into CodeHarbour?

**Comment by rteusner** [comment]
Yes, like in CodeOcean right now. You click on "add"

![bildschirmfoto 2016-01-06 um 11 51 43](https://cloud.githubusercontent.com/assets/3008882/12140958/f860dea2-b46b-11e5-8a87-0ec8bf470a9a.png)

and get forwarded to a page, that already has a key generated, that you can pass to your "trusted admin on the other side".

![bildschirmfoto 2016-01-06 um 11 51 29](https://cloud.githubusercontent.com/assets/3008882/12140973/16c7ad94-b46c-11e5-8d06-d9cf189b77c0.png)

**Comment by leoselig** [comment]
Okay, updated description

**Comment by tstaubitz** [comment]
lgtm like that
