### ISSUE TITLE
Datamodel not proforma compliant

### ISSUE THREAD

**Issue by kkoehn** [openHPI/codeharbor#420]
The current datamodel is not proforma compliant, therefore imports and exports using proforma are difficult and some information may get lost in both directions.
I tried outlining the differences and needed changes in following file
[hpi03.pdf](https://github.com/openHPI/codeharbor/files/5446046/hpi03.pdf)

Summary:
We would need a new ModelSolution model and minor changes to ExerciseFile and Test.
ExecutionEnvironment should be refactored to ProgrammingLanguage.
We could keep CH specific models like Label, Comment, Rating, Author.
Exercise itself would need deeper changes and should be named Task.

This would guarantee compatibility to proforma, but would exclude information used in CodeOcean. We could think about storing some of those in ANY fields, but I don't think this is always an option.

**Comment by MrSerth** [comment]
I like the idea of moving CodeHarbor closer to ProFormA and agree that additional information not required in ProFormA could be kept with the existing CH models.

Of course, loosing additional information used in CodeOcean hurts me. Hence, adding those (if possible) to an ANY field would be great. For those information that cannot be added, I would propose to evaluate how important they are and whether we can omit those.

**Comment by MrSerth** [comment]
With the latest refactorings, we moved more closely to the ProFormA data model. Hence, we're closing this issue.
