### ISSUE TITLE
Text content in file is not saved

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#543]
It is currently not possible to make inline changes to files at all. The changes are not persisted as shown below.

**Before save:**

<img width="1283" alt="Bildschirmfoto 2021-11-16 um 10 49 42" src="https://user-images.githubusercontent.com/7300329/141963551-b432a472-7dfa-4b43-a563-169238feb96e.png">

**After save:**

<img width="1304" alt="Bildschirmfoto 2021-11-16 um 10 49 54" src="https://user-images.githubusercontent.com/7300329/141963559-7d75a4b1-0457-403c-bde9-67920a2d45a3.png">

**Comment by kkoehn** [comment]
fixed by #716
