### ISSUE TITLE
Clean up codebase

### ISSUE THREAD

**Issue by Adrian-St** [openHPI/codeharbor#59]
- [x] Fix codesmells as suggested by Codeclimate. Set up Codeclimate in general.
- [x] Remove unnecessary columns in database 
- [ ] Remove duplicate entries in locales by adding shared entries. Rework structure.
- [x] Localize hard coded strings #76 
- [x] Restructure routes
- [x] Refactor where necessary

**Comment by MrSerth** [comment]
We're postponing the restructuring of locales to a later date when we add more translations.
