### ISSUE TITLE
Tasks: Improve search page

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#769]
Currently, the search page for tasks has the following issues:
- [x] Switch between public and my tasks seems unintuitive (but this might be more intuitive, if we have the third "private" option again)
- [x] Results are too tall (make them collapsible)
- [x] Remove edit and delete buttons (similarly, we should probably make those prominent on the show page, i.e., add a second (icon-based) button to the top right corner?)

**Comment by florian-str** [comment]
>  Switch between public and my tasks seems unintuitive (but this might be more intuitive, if we have the third "private" option again)

It was decided to use a different structure. Currently, there are three tabs with the following semantic (see #905):
- My tasks
  - This contains the tasks, the current user has created
- Group tasks
  - This contains all tasks from all groups, in which the user is a member
- Public
  - Any task with access level public

**Comment by MrSerth** [comment]
With #1359 and #1592, we improved the search page, allowing us to close this ticket.
