### ISSUE TITLE
Reimplement task duplication

### ISSUE THREAD

**Issue by kkoehn** [openHPI/codeharbor#782]
extract from small issue compilation

- [x] "Duplicate" Exercise doesn't copy labels or groups (maybe intentional)
  - labels should be copied
  -  groups should not be copied
  - [x] Duplicate task is not yet implemented
- [x] ExerciseRelation is used in a weird way (Exercise has two relations to this model)
  - refactor relation: CloneRelations should include all Clones of particular exercise. OriginRelations should be singular and the other way around

**Comment by florian-str** [comment]
A new task duplication issue was opened in #902 and is currently being addressed in #924. 

Is this issue still relevant?

**Comment by MrSerth** [comment]
Indeed, this issue is no longer relevant for the task duplication. We might still consider re-adding relations, but this should be tracked in another issue. Therefore, I am closing this issue in favor of #902.
