### ISSUE TITLE
Refactor groupify integration

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#800]
With #794, we are upgrading Rails from 6.1 to 7.0. This change affects the [`groupify` gem](https://github.com/dwbutler/groupify), which is not yet compatible with Rails 7. Unfortunately, it is unmaintained since six years, so that I don't expect that it will become compatible with Rails 7 soon. Therefore, during the upgrade, we switched to [a fork of `groupify`](https://github.com/reed/groupify/tree/rails7), that was made compatible with Rails 7.

We should investigate whether we can find a better maintained approach for the underlying issue we're solving with `groupify`.

**Comment by kkoehn** [comment]
As far as I can see, we don't use groupify to do any magic - it's only used for some basic comfort-functions around groups. I suggest removing that dependency and implementing a solution ourselves
