### ISSUE TITLE
Reimplement contributions for tasks

### ISSUE THREAD

**Issue by florian-str** [openHPI/codeharbor#930]
It should be possible, that a user can create a contribution to a public task by another user.

The workflow is supposed to be the following:

1. user B creates a contribution (T2)
2. B saves the changes -> creates an "PR"
3. An email gets sent to the members of A, which are users with write access to the original task (T1)
4. On the page of T1, there should be a notification indicating a pending contribution
5. A-users are able to approve or reject a task

In case of approval:
- Comments on T2 get dropped
- T1 gets replaced by T2
- T2 gets dropped
- all other pending contributions T3...Tn get rejected/ invalidated
- Emails

In case of rejection or edit of T1:
- T2 will be a "real duplicate"
- Emails

If T2 gets withdrawn:
- B can convert T2 to a real duplicate or select to delete the entry
- Emails

Other constraints:
- Each user may only create one active contribution per task
- Contributions can't be added to groups or collections
- Contributions can't modify the `parent_uuid`, `license` and `access_level`
- Contributions don't have ratings
- Contributions, which have not been answered for a certain (?) duration should be viewed as rejected

This issue could be implemented with the following steps:

- [x] Implementation of the basic workflow
- [x] Adding constraints to the contributions
- [x] Implementing the approval
- [x] Implementing the rejection/ withdraw/ change of original tasks
- [ ] Quality of life improvements (e.g. showing changed files)

**Comment by MrSerth** [comment]
We've implemented task contributions with #1103, which cover all mandatory steps outlined above. The quality of life improvements will be subject of a follow-up ticket.
